sudo: required
services:
  - docker

before_install:
  - docker build -t shparimi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shparimi/react-test npm test

after_success:
  - docker build -t shparimi/multi-client ./client
  - docker build -t shparimi/multi-nginx ./nginx 
  - docker build -t shparimi/multi-server ./server 
  - docker build -t shparimi/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shparimi/multi-client
  - docker push shparimi/multi-nginx
  - docker push shparimi/multi-worker
  - docker push shparimi/multi-server